Repository TheCodeXTeam/Kandahar-IHS, pull requests merged in 2020-03, with the labels that each got.

#1 relationship queries has been added
  src/main/resources/sql/db-ddl.ipynb
Labels: Effort: 5, For: Database, Priority: Critical, Status: Completed, Type: Enhancement

#3 Yasir/modify/quries
  src/main/resources/erd/KIHS-VERSION01-ERD.vpd
  src/main/resources/sql/db-ddl.ipynb
Labels: Effort: 1, For: Database, Priority: Medium, Type: Enhancement

#11 Yasir/database/erd/version02
  src/main/resources/erd/KIHS ERD version 02.vpd
Labels: Effort: 1, For: Database, Priority: High, Status: Completed, Type: Bug

#9 the check in problem has been solved
  src/main/resources/sql/db-ddl.ipynb
Labels: Effort: 2, For: Database, Priority: Medium, Type: Enhancement

#12 Yasir/database/sql/queries/change
  src/main/resources/sql/db-ddl.ipynb
Labels: Effort: 1, For: Database, Priority: High, Status: Completed, Type: Bug

#17 Yasir/ui/student-page-feature-issue
  src/main/resources/static/css/style.css
  src/main/resources/static/js/script.js
  src/main/resources/templates/Student.html
Labels: Effort: 4, For: UI, Priority: Critical, Status: Completed, Type: Enhancement

#15 Elham/ui/login/html,css codes
  src/main/resources/static/css/style.css
  src/main/resources/templates/Login.html
Labels: Effort: 2, For: UI, Priority: Low, Status: Completed, Type: Enhancement

#22 The html code has been added for teacher page.
  src/main/resources/templates/Teacher.html
Labels: Effort: 2, For: UI, Priority: Medium, Status: Completed, Type: Enhancement

#23 Elham/ui/teacher/address,experience,educational background
  src/main/resources/templates/Teacher_Address.html
  src/main/resources/templates/Teacher_Educational_Background.html
  src/main/resources/templates/Teacher_Experience.html
Labels: Effort: 3, For: UI, Priority: Medium, Status: Completed, Type: Enhancement

#27 Employee UI page added.
  src/main/resources/templates/Employee.html
Labels: For: UI, Status: Completed

#34 Naveed/db/test queries
  src/test/resources/sql/db-ddl-test.ipynb
Labels: Effort: 3, For: Database, Priority: High, Status: Completed, Type: Maintenance
